products:
    - name: Milk
      base_price: 1.5
      inventory: 100
      icon: "ğŸ¥›"
    - name: Bread
      base_price: 1.1
      inventory: 100
      icon: "ğŸ"
    - name: Eggs
      base_price: 1.00
      inventory: 100
      icon: "ğŸ¥š"
    - name: Cheese
      base_price: 6.5
      inventory: 100
      icon: "ğŸ§€"
    - name: Meat
      base_price: 7.67
      inventory: 100
      icon: "ğŸ¥©"