products:
    - name: Milk
      base_price: 1.5
      inventory: 20
      icon: "ğŸ¥›"
    - name: Bread
      base_price: 1.1
      inventory: 25
      icon: "ğŸ"
    - name: Eggs
      base_price: 3.45
      inventory: 21
      icon: "ğŸ¥š"
    - name: Cheese
      base_price: 6.5
      inventory: 17
      icon: "ğŸ§€"
    - name: Meat
      base_price: 7.67
      inventory: 15
      icon: "ğŸ¥©"